[project]
name = "upsum"
version = "0.9.1"
description = "Add your description here"
authors = [
    { name = "Nate Doohyun Jang", email = "1220430+lum7671@users.noreply.github.com" }
]
dependencies = [
    "google-genai>=2.12.1",
    "jinja2>=3.1.6",
    "markdown-it-py>=4.0.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "python-dotenv>=1.2.2",
    "sysutils",
]
readme = "README.md"
requires-python = ">=3.13.2"

[project.scripts]
upsum = "upsum.__main__:main"

[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

