import re
from pathlib import Path
import json

# 전처리 규칙에 따라 의미 없는 줄을 제거하고, 핵심 이벤트만 남기는 파서

def is_noise(line: str) -> bool:
    # 의미 없는 진행률/중복/상태 메시지/경로/해시 등 제거
    noise_patterns = [
        r"^\s*$",  # 빈 줄
        r"\(데이터베이스 읽는중",  # debconf 등
        r"^받기:",
        r"^기존:",
        r"^Hit:",
        r"^Get:",
        r"^Fetched ",
        r"^내려받기 ",
        r"^Reading package lists",
        r"^패키지 목록을 읽는 중입니다",
        r"^의존성 트리를 만드는 중입니다",
        r"^상태 정보를 읽는 중입니다",
        r"^debconf:",
        r"^SUCCESS: .+ updated$",
        r"^이미 업데이트 상태입니다",
        r"^default -> lts/\*",
        r"^15 packages are looking for funding",
        r"^run `npm fund` for details",
        r"^changed \d+ packages in",
        r"^\* \[새로운 브랜치\]",
        r"^\* \[새로운 태그\]",
        r"^\+ ",
        r"^\- \[삭제됨\]",
        r"^origin을\(를\) 가져오는 중",
        r"^upstream을\(를\) 가져오는 중",
        r"^\s*Fast-forward$",
        r"^\s*UN.*CHANGED.*$",
        r"^\s*SUCCESS: .+",
        r"^\s*ERROR: .+",
        r"^\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
        r"^\s*\|\s*\d+ insertions\(\+\), \d+ deletions\(-\)",
        r"^\s*\|\s*\d+ insertions\(\+\)",
        r"^\s*\|\s*\d+ deletions\(-\)",
        r"^\s*\|\s*\d+ files changed",
    ]
    for pat in noise_patterns:
        if re.search(pat, line):
            return True
    return False

if __name__ == "__main__":
    src = Path("logs/update_all-20260520_023109.log.001")
    dst = Path("logs/update_all-20260520_023109.001.cleaned.log")
    with src.open(encoding="utf-8") as f, dst.open("w", encoding="utf-8") as out:
        for line in f:
            if not is_noise(line):
                out.write(line)
